### ISSUE TITLE
Markdowns tool issues

### ISSUE THREAD

**Issue by Mahmoud-Emad** [crystaluniverse/crystallib#107]
@despiegk @xmonader 
Now the code compiling without raising errors, but when running the examples it fails, I think that's because of the refactor, so I'm asking, whether should I work on it.

**Comment by Mahmoud-Emad** [comment]
WIP: 
Added parser line helper functions to parse the current line and get its type.
inside the parse_doc function, we get the whole code until the end.

**Comment by despiegk** [comment]
I finished an implementation should be ok now
