### ISSUE TITLE
markdowndocs improvements

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#115]
**branch: development_docker**

* make tests for may usecases (links, comments, mixed, ...)
* see that wiki representation is always ok
* check todo's
* create a table parser & representation part

the idea is that we can safely parse and always represent the parsed document in good way, this allows us to manipulate wiki documents with eas

**Comment by despiegk** [comment]
...crystallib/markdowndocs/wiki_test.v

has quite some issues and need way more tests

**Comment by brandonpille** [comment]
@despiegk can you please verify the changes so we can close this issue?
