### ISSUE TITLE
finish sheet module

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#117]
see development_docker branch

## sheet to quarter and year representation

* see function sheet.toyear() ... same for quarter

## implement sheet.header()

* see header function, idea is we return properly names for the headers in line to purpose of sheet

## sheet -> wiki implementation

* output markdown
* use tables
* format tables nicely (so all fields have same width = max width of 1 column): use sheet.len_col_max() for that
* the header is as given by sheet.header()

## sheet -> html representation

* create function which uses templates to create html page
* embed the javascript files needed ($embed)
* make nice representation of the sheet struct
* make headers, which is month 1 ...60 (depending nr columns)
* allow an optional argument to define which rows to output and order (list of names of rows), only visualize those
  * see toyear in sheet.toyear()
* select a nice javascript library

## doc/tests

* make some more tests & complete help text

## json()

* see sheet.json()
* this can be handy to have behind webserver so can be embedded in remote html widget

## group2row()

* see sheet.group2row()

## cell/row get

* see functions

**Comment by zaelgohary** [comment]
Branch development_docker is probably deleted as it's not part of the [branches](https://github.com/freeflowuniverse/crystallib/branches).

**Comment by despiegk** [comment]
what is progress, see Brandon he can help for brach

**Comment by Omarabdul3ziz** [comment]
according to Brandon the `development_docker` branch is renamed to `development` and it is the default branch now. we started working on the issue. will keep the issue updated

**Comment by Omarabdul3ziz** [comment]
Updates till now.
we implemented a parser that take CSV string and convert it to 2D array. 
and also three converter to md, html and map object.

```vlang
mut sh := Sheet{}
sh.raw_data = 
"Name,Position,Salary
Foo,SWE ,0
Bar,SWE II,0
Baz,SWE,0"
sh.parse()
```

```vlang
sh.to_md() 
```
will generate
|Name|Position|Salary|
|---|---|---|
|Foo|SWE |0|
|Bar|SWE II|0|
|Baz|SWE|0|	

```vlang
sh.to_html(<table_styles>)
```
![image](https://user-images.githubusercontent.com/32527347/223747468-c00aff50-4018-4518-9d31-4981287ebdb2.png)

```vlang
sh.to_json()
```
will generate 
```json
[
   {
      "Name":"Foo",
      "Position":"SWE ",
      "Salary":"0"
   },
   {
      "Name":"Bar",
      "Position":"SWE II",
      "Salary":"0"
   },
   {
      "Name":"Baz",
      "Position":"SWE",
      "Salary":"0"
   }
]
```

Still working on the other parts

**Comment by despiegk** [comment]
- needs to use $tmpl & $embed to make sure all relevant files are compiled in
- generate html which shows a nice sheet coming from data from the sheet object
- maybe we can even do this for multiple sheets which become tabs?
