### ISSUE TITLE
create grid SAL

### ISSUE THREAD

**Issue by mariobassem** [crystaluniverse/crystallib#130]
to create a SAL for the grid, using the cli from (https://github.com/threefoldtech/grid3_client_go), the following is required:

* an action is pushed to some redis queue using vlang SAL
* an action listener picks the actions and starts to process them, then returns back the action result.
* vlang SAL waits for the action result until it's processed.

this is doable but would require implementing a messaging system in the proposed vlang SAL, and in wherever the action listener is.
but this is already implemented in rmb.

so, one way to do it is to create a twin for the grid client, then use rmb to send/receive actions to/from this twin.
but this would require one of two things:

* running an rmb peer in the SAL.
* use a direct client binary.

**Comment by despiegk** [comment]
I think we’re making this too complicated

did you check the RPC message thing I quickly made in V

its just a 

- epoch
- cmd
- data

from a queue an return queue

don’t drag in new components, its not worth it

I made the full RPC in Vlang in 30 min

doing the processor side in GOLang should not take much more time

suggest to go back to simplicity

**Comment by despiegk** [comment]
ps: the rpc mechanism is not a SAL, a SAL is an abstraction layer on top of an external system !

**Comment by despiegk** [comment]
see the story about web3proxy
