### ISSUE TITLE
create routeros configurator

### ISSUE THREAD

**Issue by ashraffouda** [crystaluniverse/crystallib#131]
we need a routeros configurator which model the required configs from routeros like vlans, addresses ... and then we can modify those config and apply it back on routeros

**Comment by ashraffouda** [comment]
so far I added the model and parser code for some component and also implemented the stuff for apply the config to router os but it now just prints the config until ssh lib is done
https://github.com/freeflowuniverse/crystallib/commit/3ea2d1d41842b062381ce72336cc0e8d00a58a06

**Comment by despiegk** [comment]
why do we need sshlib

**Comment by despiegk** [comment]
the basics are ok for a first release

**Comment by ashraffouda** [comment]
> why do we need sshlib

as far as I remember this was needed to execute the commands on routerOS, I remember when we checked the rpc thing it was not supported, writing the full config file also not working, when we were in zanzibar @maxux  was working on adding the sshlib, not sure if it is done or not 
so writing the config will happen through ssh config

**Comment by maxux** [comment]
It was nearly done and I could get some config write and query working on the routeros we had in Zanzibar.
There were reliable other way to send command to routeros. Additionnally that was giving full ssh support to vlang with a stable library.
