### ISSUE TITLE
implement zerohub module 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [crystaluniverse/crystallib#136]

**Comment by Omarabdul3ziz** [comment]
work is done at `development_gridClient` in `threefold/zerohub/`

**Comment by despiegk** [comment]
check docu

**Comment by despiegk** [comment]
move to web3gw code & docu & task

**Comment by despiegk** [comment]
please contact me to review

**Comment by despiegk** [comment]
part of the story for end2end tfhub
