### ISSUE TITLE
libssh2: bind ssh library to v

### ISSUE THREAD

**Issue by maxux** [crystaluniverse/crystallib#152]
Finish binding of libssh2 (via https://github.com/maxux/vssh) to crystallib.

**Comment by maxux** [comment]
In progress

**Comment by despiegk** [comment]
what is status?

**Comment by maxux** [comment]
Blocked, had no time to finish it. Will put it on todo list for next scheduled project.

**Comment by maxux** [comment]
Unblocked, working on it.

**Comment by maxux** [comment]
Current status, coming features are really interesting !

- [x] Supports keyboard-interactive, old password and ssh-agent login
- [x] Support sending commands
- [x] Efficient stdout management
- [x] Streaming callback support
- [ ] File upload / download (scp)
