### ISSUE TITLE
params: get list should be improved

### ISSUE THREAD

**Issue by brandonpille** [crystaluniverse/crystallib#179]
The get_list function does not properly parse lists. It does not allow for comma's in the items from the list. For example what if we want a list of the following strings: "NVIDIA, gtx 1080", "NVIDIA, gtx 1080ti". The parser will parse this list as 4 items while there are only 2. 

We should improve the parser and add tests.

**Comment by xmonader** [comment]
definitely, commas enclosed within single/double quoted strings should be ignored

**Comment by brandonpille** [comment]
Indeed. I'll do this one now as I do need it for the gpu parsing in the farmerbot
