### ISSUE TITLE
Create jsonrpc server and client

### ISSUE THREAD

**Issue by timurgordon** [crystaluniverse/crystallib#186]
JSON-RPC WebSocket server and client code in the jsonrpc module can help standardize and simplify creating servers and clients for json-rpc projects. Unfortunately https://github.com/nedpals/v-jsonrpc is outdated but can be used for inspiration. HTTP servers and clients can be added in the future.

**Comment by timurgordon** [comment]
server and client implementation in [jsonrpc](https://github.com/freeflowuniverse/crystallib/tree/186-create-jsonrpc-server-and-client/jsonrpc).

For the server, I created a `IRpcHandler` interface in` rpcwsserver`  908b023 and replaced the `handler` function with that f4e7a08. This was because I needed to pass additional context to the server that the handler function didn't suffice for. Do you think this change is okay @brandonpille ? I then added a` JsonRpcHandler` that implements the `IRpcHandler` interface and passed it to rpcwsserver to create a jsonrpc ws server. 833042f

For the client, I had to move the `rpcwsclient.send_jsonrpc method` to `jsonrpc/client.v` to keep the rpcws module general and avoid circular imports. Might this be a breaking change? The rpcwsclient is passed into the `IJsonRpcClient` as a transport client. 

```
pub interface IRpcTransportClient {
mut:
        send(string, int) !string
}

pub interface IJsonRpcClient {
mut:
        transport IRpcTransportClient
}

pub fn (mut client IJsonRpcClient) send_json_rpc[T, D](method string, data T, timeout int) !D {
        json_rpc_request := new_jsonrpcrequest[T](method, data)
        response := client.transport.send(json_rpc_request.to_json(), timeout)!
        error_check := jsonrpcerror_decode(response) or {
                jsonrpc_response := jsonrpcresponse_decode[D](response) or {
                        return error('Unable to decode ${response}')
                }
                if jsonrpc_response.id != json_rpc_request.id {
                        return error('Received response with different id ${response}')
                }
                return jsonrpc_response.result
        }
        return error('Error ${error_check.error.code}: ${error_check.error.message}')
}
```
https://github.com/freeflowuniverse/crystallib/blob/9f2446116eebc11257dd0789d18e6a8cfddd0a8a/jsonrpc/client.v#L5C1-L29C2

**Comment by brandonpille** [comment]
Why is the IJsonRpcClient an interface? You typically would make it an interface if it could have many different implementations but in this case it doesn't. It is a good idea to do so if you would want to be able to mock it out in tests. But in that case you would have the interface and a struct too:

```
pub interface IJsonRpcClient {
mut:
        transport IRpcTransportClient
        send_json_rpc[T, D](method string, data T, timeout int) !D
}

pub struct JsonRpcClient {
pub mut:
       transport IRpcTransportClient
}

pub fn (mut client JsonRpcClient) send_json_rpc[T, D](method string, data T, timeout int) !D {
        json_rpc_request := new_jsonrpcrequest[T](method, data)
        ....
}
```

Now you can keep an object of type IJSonRpcClient, use JsonRpcClient in production and write your own mock for it too.

**Comment by brandonpille** [comment]
What was the additional context?

**Comment by brandonpille** [comment]
Why do we want rpc over http? If it's not needed then I would suggest to wait with that. We have other more urgent work.

**Comment by timurgordon** [comment]
> Why is the IJsonRpcClient an interface? You typically would make it an interface if it could have many different implementations but in this case it doesn't. It is a good idea to do so if you would want to be able to mock it out in tests. But in that case you would have the interface and a struct too:
> 
> ```
> pub interface IJsonRpcClient {
> mut:
>         transport IRpcTransportClient
>         send_json_rpc[T, D](method string, data T, timeout int) !D
> }
> 
> pub struct JsonRpcClient {
> pub mut:
>        transport IRpcTransportClient
> }
> 
> pub fn (mut client JsonRpcClient) send_json_rpc[T, D](method string, data T, timeout int) !D {
>         json_rpc_request := new_jsonrpcrequest[T](method, data)
>         ....
> }
> ```
> 
> Now you can keep an object of type IJSonRpcClient, use JsonRpcClient in production and write your own mock for it too.

The idea is that separate JsonRpcClients can implement the interface and add methods on top of it. Having the send_rpc method an interface method allows it to be able to called by all jsonrpcclients that implement the interface. An alternative would be to embed the struct you mention here into the clients, which makes more sense so I can switch to using it that way instead.

**Comment by timurgordon** [comment]
> What was the additional context?

For my mock mail memory server, a map of procedure name to handler (this isn't absolutely necessary since such can be hardcoded into the handler function, but makes code a lot cleaner), and a reference to the mail model. The reference allows the handler to modify and access a memory state. This additional context could also include a channel to a process thread so incoming requests can be queued, or a database connection using a database pool.

For instance this [counter test](https://github.com/freeflowuniverse/crystallib/blob/485e6b721ffea54ddd586220a7cd8e5236255724/jsonrpc/handler_test.v#L50-L97) shows how the handler can hold and modify state:
```
struct Counter {
mut:
        count int = 0
}


struct CounterJsonRpcHandler {
        JsonRpcHandler
}


pub fn (mut counter Counter) increment(steps int) !int {
        counter.count += steps
        return counter.count
}


pub fn (mut handler CounterJsonRpcHandler) increment_handler(data string) !string {
        request := jsonrpcrequest_decode[int](data)!
        mut counter := &Counter(handler.state)
        result := counter.increment(request.params)!
        response := JsonRpcResponse[int]{
                jsonrpc: jsonrpc_version
                id: request.id
                result: result
        }
        return response.to_json()
}


fn test_stateful_handle() {
        mut logger := log.Logger(&log.Log{
                level: .debug
        })
        counter := Counter{}
        mut handler := CounterJsonRpcHandler{
                JsonRpcHandler: new_handler(&logger)!
        }
        handler.state = &counter
        handler.register('increment', handler.increment_handler)!

        request0 := new_jsonrpcrequest[int]('increment', 2)
        result0 := handler.handle(request0.to_json())!
        response0 := jsonrpcresponse_decode[int](result0)!
        assert response0.result == 2

        request1 := new_jsonrpcrequest[int]('increment', 3)
        result1 := handler.handle(request1.to_json())!
        response1 := jsonrpcresponse_decode[int](result1)!
        assert response1.result == 5
}
```

**Comment by timurgordon** [comment]
> Why do we want rpc over http? If it's not needed then I would suggest to wait with that. We have other more urgent work.

We don't need rpc over http, just ws, so I'm not working on it. However, for now, I tried to make the JsonRPC handler and client modular enough so we could use them with alternative transports, http, rmb.
