### ISSUE TITLE
integrate in development_integration

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#190]
* close all branches but development and development_integration, communicate with all involved
* **everyone for now works on development_integration**
* branches which cannot be integrated but we don't want to loose copy to  _archive/$modulename put readme if relevant
* only urgent matters on milestone 1.0.0 which are needed for minimal version of 3bot v 1.0.0, rest to next or later milestone
* all code to do with threefold move to web3gw repo
* in our main libraries all tests need to work

**Comment by brandonpille** [comment]
Fixed the failing tests and removed tfgrid part from threefold folder as we don't need it and already have it in the web3gw
