### ISSUE TITLE
Twinsafe

### ISSUE THREAD

**Issue by ashraffouda** [crystaluniverse/crystallib#211]
finish implementation for twinsafe module which stores twin info in local sqlite db

**Comment by ashraffouda** [comment]
implementation is almost done, except for the part for send/receive and verify data, will be done after secp256k1 implementation is fixed https://github.com/freeflowuniverse/crystallib/issues/205

**Comment by alichaddad** [comment]
Verify data part is done, send/receive will be worked on when `mbus` implementation is done
