### ISSUE TITLE
knowledgetree/examples not working + lots of other things still broken

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#219]
/Users/despiegk1/code/github/freeflowuniverse/crystallib/knowledgetree/example

**Comment by despiegk** [comment]
in the scandir example which has been made to work there are issues

- duplicate pages are not found, it ignores it
- a weird link is being made pointing to nothing with name of collection
- many of the pages created were actually empty
- fix links was not done on export when healing not looked for

**Comment by despiegk** [comment]
<img width="768" alt="image" src="https://github.com/freeflowuniverse/crystallib/assets/6021844/dbe17da2-1f1f-4cf7-aa2c-4e8c3af76325">
couldn't work would error before checking if file exists

has been rewritten in other way

**Comment by despiegk** [comment]
- most of pages exported are empty
- the include macro not implemented !!include collectionname:aname and aname needs to be supported
- we reworked where we export book too, there is now default destination
- if healing not on on collection level, then we still need to make sure that files get resized at destination, same for links
- double check that we get links to work e.g. [mylink](collection:pagename.md) should rewrite link (only at destination) if collection not specified then in collection it was defined

**Comment by brandonpille** [comment]
> <img alt="image" width="768" src="https://user-images.githubusercontent.com/6021844/261195027-dbe17da2-1f1f-4cf7-aa2c-4e8c3af76325.png"> couldn't work would error before checking if file exists
> has been rewritten in other way

Why wouldn't it work. It does work, I have tests. It will not throw an error and it returns even if the file does not exist. Take a look at the code under pathlib.

**Comment by brandonpille** [comment]
> * most of pages exported are empty
> * the include macro not implemented !!include collectionname:aname and aname needs to be supported
> * we reworked where we export book too, there is now default destination
> * if healing not on on collection level, then we still need to make sure that files get resized at destination, same for links
> * double check that we get links to work e.g. mylink should rewrite link (only at destination) if collection not specified then in collection it was defined

I have some more questions:
- Can you share with me the examples that resulted in empty pages? And are you sure there weren't any errors in the errors.md file? 
- Where can I find examples for the macro include
- What do you mean with "we reworked where we export book too, there is now default destination"? What should I change?
- I didn't change anything to the healing part so can you elaborate more on the fourth bullet point? Could you please document the healing part? What should it do?
- What does the last bullet point mean? If there is a link without the name of the collection it should be rewritten to include the name of the collection where the link is defined in?
