### ISSUE TITLE
sendgrid client

### ISSUE THREAD

**Issue by xmonader** [crystaluniverse/crystallib#226]
part of https://github.com/threefoldtech/home/issues/1461

basic client to send email https://github.com/sendgrid/sendgrid-python
sample api in python

```python
# using SendGrid's Python Library
# https://github.com/sendgrid/sendgrid-python
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

message = Mail(
    from_email='from_email@example.com',
    to_emails='to@example.com',
    subject='Sending with Twilio SendGrid is Fun',
    html_content='<strong>and easy to do anywhere, even with Python</strong>')
try:
    sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
    response = sg.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except Exception as e:
    print(e.message)
```

**Comment by 0oM4R** [comment]
WIP: https://github.com/freeflowuniverse/crystallib/tree/development_sendGrid

**Comment by mariobassem** [comment]
currently, all types needed are implemented and are publicly accessible.
the client has a method to send a simple email to multiple recipients.
an example is also provided for sending a simple email.

what is left is creating a proper factory function for the client, fixing some typos, and accepting command line arguments in the example.

**Comment by 0oM4R** [comment]
all functionality is done and readme is added; will modify the read me and create the PR
