### ISSUE TITLE
Test and separate publishingtools 

### ISSUE THREAD

**Issue by rkhamis** [crystaluniverse/crystallib#230]
As per https://github.com/threefoldtech/home/issues/1463, the following needs to be done

* [ ] find the software (see master branch on crystallib), or more recent
* [ ] copy the code itself to publishing tools repo (freeflow universe)
* [ ] copy the macro's as well
* [ ] make sure it builds
* [ ] make sure we have a vbuilder for building the publishing tools
* [ ] run them in development mode, check them against library.threefold me, is it all working
* [ ] create a v script starting docker with the publishing tools, checkout info_legal and info_... load them all show the result in webserver from publishing server
* [ ] check the export function of publishing server
* [ ] make sure all docu is on publishing tool server

**Comment by despiegk** [comment]
these are the old publishing tools
