### ISSUE TITLE
osal.docker v 1.0.0

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#241]
> branch: `development_docker`

## features

* good sal for docker for compose, build, basics run, ...

## requirements

* good examples
* should be super easy for someone to operate docker for all basic workflows

## to resolve

see also

* https://github.com/freeflowuniverse/crystallib/issues/210
* https://github.com/freeflowuniverse/crystallib/issues/206

**Comment by 0oM4R** [comment]
WIP: 
- fixed building errors in docker module 
- we added two examples
  - TF Dashboard
  - Development environment that contains [ zinit, ssh, vim ]

**Comment by 0oM4R** [comment]
We tried to use as many recipes by adding three examples : 
 - TF Dashboard
 - Development environment that contains [ zinit, ssh, vim ]
 - Presearch __Compose__
 
 if you have any specific example please tell us.
