### ISSUE TITLE
gitea + chosen oauth solution

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#254]
* deploy gitea (use v installer, see kristof)
* test oauth solutions
* create bash script (or v installer) to install chosen oauth solution

# oauth solution criteria

* prefer go or rust (prefer not to use js or python)
* users can administer their own email, ...
* users can set description, tel, email, ...
* can login into gitea
* will be easy to adjust so we can set/get user details in other chosen system (e.g. our 3bot)

## Some foundational requirements for an OAuth2 server (chatgpt):

 1. **Protocols and Grant Types**:
    * Support for standard OAuth2 grant types: Authorization Code, Implicit, Client Credentials, Password, and Refresh Token.
    * Optionally support for extension grant types, such as JWT bearer token exchange.
    * Support for Proof Key for Code Exchange (PKCE) to mitigate authorization code interception attacks, especially for mobile and single-page apps.
 2. **Client Management**:
    * Ability to register and manage clients (applications).
    * Secure storage of client secrets.
    * Support for public clients (e.g., mobile apps) where secrets can't be kept confidential.
    * Ability to specify and enforce redirect URIs.
 3. **Token Management**:
    * Generation and validation of access tokens, optionally refresh tokens.
    * Secure token storage (if storing tokens).
    * Ability to set and manage token lifetimes.
    * Support for token introspection and revocation.
 4. **User Authentication and Consent**:
    * Integration with existing user authentication systems (like LDAP, SSO systems).
    * Support for multi-factor authentication.
    * A user interface for granting and managing user consent.
 5. **Scopes and Claims**:
    * Define and manage scopes for limiting access.
    * Allow clients to request specific scopes.
    * Support for OpenID Connect (OIDC) if also acting as an identity provider.
 6. **Security**:
    * Ensure all communication is over TLS.
    * Protection against common web vulnerabilities (CSRF, XSS, Clickjacking).
    * Token information confidentiality, either by using opaque tokens or by encrypting JWT tokens.
    * Proper error handling without revealing sensitive information.
 7. **Logging and Auditing**:
    * Logging of all authorization and token requests.
    * Auditing capabilities for security incidents and to satisfy regulatory requirements.
 8. **Extensibility and Integration**:
    * Ability to plug into external user stores (e.g., custom user databases, LDAP).
    * Extensibility to support custom grant types, scopes, or token formats.
    * Integration with existing logging, monitoring, and alerting tools.
 9. **User and Developer Portals**:
    * A portal for end-users to manage their granted consents.
    * A developer portal for client registration, documentation, and possibly testing.
10. **Documentation**:
    * Good enough documentation for developers about integrating with the OAuth2 server.
    * Administrative documentation on how to maintain, monitor, and troubleshoot the server.
11. **Compliance and Interoperability**:
    * Adherence to the OAuth2 and OIDC specifications.
    * Periodic security assessments and penetration testing.

**Comment by despiegk** [comment]
install on ununtu 22.04 on grid

**Comment by delandtj** [comment]
id.meet.tf ? that vm ?

**Comment by despiegk** [comment]
check 
- hydra: https://github.com/ory/hydra
- authentik
- zitadel

**Comment by despiegk** [comment]
should all be using out v installers, maybe the building can happen in our new sandboxer

**Comment by despiegk** [comment]
@delandtj please put link to where the work has been done and what status us
