### ISSUE TITLE
check threefold/rmb, do we need it, is it double with threefold/grid

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#256]
https://github.com/freeflowuniverse/crystallib/tree/development/crystallib/threefold/rmb

would be better to have 1 way how to work

**Comment by mariobassem** [comment]
the two clients have different approaches:
- the griddriver (used in threefold/grid) uses the go direct client, which basically opens a websocket connection directly with the relay, sends the request, and waits for the response
- the rmb client (threefold/rmb) has an rmb-peer server running, along with a redis server, and can send/receive requests/responses.

taking into consideration that the griddriver is already used in other modules, while the rmb module is not, and also the rmb module could easily be replaced by the redis client directly, which is the implemented approach in farmerbot, we believe that it's better to stick with the griddriver approach.

**Comment by Omarabdul3ziz** [comment]
## Update: 

we go with implementing a client that uses the griddriver binary here: https://github.com/freeflowuniverse/crystallib/pull/264


PR contains:
- generic `rmb_call` method that can forward any rmb request
- some call to the substrate
- other needed utils

## Note:
we are using the griddriver binary at [6bb56f6796381c6faa0511a8d6f5551d300548f6](https://github.com/threefoldtech/web3gw/commit/6bb56f6796381c6faa0511a8d6f5551d300548f6). it is on `developemnt_integration` branch now
