### ISSUE TITLE
peertube installer

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#257]
> branch `development_peertube`

* create installer for peertube
* make example how to install/configure
* simple client for rest api, just to upload a video to it (delete)

## research

* can we do CDN with peertube
* test X nr of peertube on grid
* document all findings, put in readme in the peertube install dir
* test rest api
* how to use with mycelium network

**Comment by maxux** [comment]
Missing:
- [ ] Implement `SCRAM-SHA-256` in V to generate Postgres password to automate deployment
- [ ] Make input settings generic to collect configuration
- [ ] Update YAML file with proper configuration settings
- [ ] Ensure `certbot` or any certificates are reused or backup, to reinstall
