### ISSUE TITLE
Knowledgetree working example to demo all functionality, edge cases and error cases

### ISSUE THREAD

**Issue by timurgordon** [crystaluniverse/crystallib#277]
freeflowuniverse/crystallib/examples/knowledgetree/directory_scan/scan.v

One example to demonstrate
- includes
- link fixing
- image resizing
- error reporting

**Comment by timurgordon** [comment]
Commits: 
- 23d0bc1f4cbd233e434c51186aaae7551dc8468b
- 1d7dda64d7dc4bc046fb0700b786c1756968d9c4
- ceebe5a4faa1706b3f206b737d5b4ca8eee7d667
- 6e035e92a4d65f6b5f95381d0f75a8ab8e620aec 
fix issues with `core.pathlib` that caused errors.

commits: 
- ab96a9cd5339fd7d74ae5fbe665fbb23d3529c02
- cca7b1d9c9944ca59fe7001ec9bd28806beb5985
- 2a028352eb473bd3b7c8abc05439621c03242aa5
fix issues with page processing

commits: 
- 83c49cfd4682d9bd5c2dc8311d77decc47d4ded5
- ec5e029c907fd5fc610f26042cb2fcbba2f58147
- 93a4173517e183307068a78889116c8422a7a6b0
improve example to demonstrate requirements

**Comment by despiegk** [comment]
kristof needs to check
