### ISSUE TITLE
baobab db v1.0

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#281]
> on branch  `development_baobab`

see https://github.com/freeflowuniverse/crystallib/blob/development/examples/baobab/db/db1.v

finish this example and its todo's

## why

* if this works well this can be the generic backend for autogenerated code
* better not to autogenerate this part, would be too errorprone maybe and also add lots to binary size

**Comment by timurgordon** [comment]
@MarioBassem also check https://github.com/freeflowuniverse/crystallib/tree/development/research/baobab/actor_backend for some of the separate progress on this. Using generics for standard crud operations instead of `paramslib.params` could be a cleaner solution.

**Comment by despiegk** [comment]
@timurgordon the task here is something different, has nothing to do with params, its a generic backend which can be used for autogeneration tools like yours

**Comment by despiegk** [comment]
@MarioBassem can you please finish this story, the example as mentioned above has not been implemented.

**Comment by mariobassem** [comment]
i did the write, read, query, delete functions. i think we need to add batch insert too, but don't know if it's needed.

also, i don't get the notion of gid, cid, oid. the `data` table stores all records from all tables in the database, but there is no notion of which table is this record from, only a `cid` and an `oid`. does this mean that a `cid` and an `oid` are unique per database??

**Comment by despiegk** [comment]
see also https://github.com/freeflowuniverse/crystallib/issues/288

**Comment by despiegk** [comment]
batch insert not needed, indeed cid was not needed, good catch

**Comment by timurgordon** [comment]
- 0b235a28ffe06b4cf0f424633c44f707131dd592 and 0b6b3b86b3d945689060618294ef1a0fe1cdd780 add reflection support and tests for baobab db
- 4b3556bc37a1fa09ba190cb1c98c521654e20640 completes example demonstrating requirements from baobab db
