### ISSUE TITLE
implement (finish) zinit sal

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#282]
see https://github.com/freeflowuniverse/crystallib/tree/development/crystallib/osal/zinit

> branch : `development_zinit`

**Comment by despiegk** [comment]
https://github.com/freeflowuniverse/crystallib/blob/development_zinit/crystallib/osal/zinit/rpc_test.v
this test doesnt seem to be a test, hello doesn't mean anything, there should be a real command starting, stopping, check the log to see the output is right, if killing the program zinit should notice, ...

**Comment by despiegk** [comment]
create an end2end example in example folder, so its easy for people to see how to use

**Comment by mariobassem** [comment]
redid the test, and created an example
