### ISSUE TITLE
finish models/system 

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#288]
* implement some more tests
* check the TODO's

this is an important class, its our base

see development_db branch, finish there

**Comment by despiegk** [comment]
check behavior with authors should be using the optionals

**Comment by mariobassem** [comment]
- added find_remarks method
- fixed and updated tests

**Comment by despiegk** [comment]
there is a first working version on development_db
we need more tests in code/github/freeflowuniverse/crystallib/crystallib/baobab/db

- [x]  see if the remarks serialization/deserialization work
- [x] check 3script serialization/deserialization
- [x] more tests
- [x] tests for find (based on time, int/string arguments, ...)

example /Users/despiegk1/code/github/freeflowuniverse/crystallib/examples/baobab/db/binaryserialization/db1.v

**Comment by mariobassem** [comment]
3script serialization/deserialization now works.

**Comment by mariobassem** [comment]
updated 3script serialization/deserialization to not use base64 encoding.
added more tests and fixes for find method.
