### ISSUE TITLE
implement client to mycelium

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#290]
see https://github.com/threefoldtech/mycelium

implement all openrpc methods

## option 1

* create an openrpc client generator for V (would be coolest, but we need it < 2 days and be sure)

## option 2

* manual client creation

**Comment by ashraffouda** [comment]
code almost done https://github.com/freeflowuniverse/crystallib/blob/development-myceilum/crystallib/clients/myceilum/mycelium.v
still need to test some functionality but for some reason myceilum stopped working with me with this issue https://github.com/threefoldtech/mycelium/issues/40

**Comment by ashraffouda** [comment]
code is implemented here https://github.com/freeflowuniverse/crystallib/pull/299/files

**Comment by ashraffouda** [comment]
all methods here are implemented https://github.com/threefoldtech/mycelium/blob/master/docs/api.yaml
