### ISSUE TITLE
V based deployment SAL for TFGrid

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#297]
* review deployment from V using the small tfgrid driver
* check the code is it there
* check is in manual
* check is documented well enough in the code
* check there are instructions how to build the tfgrid driver
* implemented as a proper SAL

## acceptance

* [ ] kristof has reviewed
* [x] can deploy/delete VM
* [x] can deploy ZDB
* [x] can deploy webgw
* [x] can add webgw to existing vm
* [x] can view contracts
* [x] know which webgw's there are (means we know how to deploy where)
* [x] can see my contracts, delete
* [x] can see how much money we are using per contract per month
* [x] where is manual how to use
* [x] are there examples in examples dir
* [x] is code properly documented, e.g. we understand each unit

**Comment by ashraffouda** [comment]
@despiegk  view contracts already implemented in grid proxy, there was a bug in it, fixed it there and added it in the examples 
https://github.com/freeflowuniverse/crystallib/pull/302
for the point ` know which webgw's there are`, this is already exists in view contracts, is this enough?
also for the point `can see how much money we are using`  there is an endpoint in grid proxy which shows the bill, is this what we need to provide? and should calculate the total or just get the last bill?

**Comment by despiegk** [comment]
- view webgw's means, we know where we can deploy a http webgw, user needs to know which gw's there are, how else can he/she make right selection
- also when we check on a VM, we need to be able to see which webgw is configured to that VM (can be more than 1)
- last bill is already do something
- is there a way how we can see how much TFT we use per day for a contract?

**Comment by ashraffouda** [comment]
docs added to the pr https://github.com/freeflowuniverse/crystallib/pull/302/commits

**Comment by ashraffouda** [comment]
- added billing (gets hourly rate for any contract) to grid proxy
-  added list gateways
all with examples https://github.com/freeflowuniverse/crystallib/commit/705fabffb14ae62d5b867f4a9488af1858fdfe0f

**Comment by ashraffouda** [comment]
added wire guard generation to web3gw and crystallib instead of generating it manually

**Comment by despiegk** [comment]
things seem to be broken, we should also use the new config mgmt classes so we can remember grid keys
