### ISSUE TITLE
client generator for openapi v3

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#305]
starting points

info

* https://github.com/despiegk/ai_playground/tree/main/openai/prompts/openapi
* https://github.com/freeflowuniverse/crystallib/tree/development_db/crystallib/core/openapi

tips

* don't generate all details, expand the httpclient and our own crystal json to give you the primitives you need, keep the generation as concise as possible

**Comment by despiegk** [comment]
test it on https://github.com/dagu-dev/dagu

**Comment by despiegk** [comment]
test on gitea

**Comment by despiegk** [comment]
test on https://www.cloudhypervisor.org/

**Comment by mariobassem** [comment]
was working with @ashraffouda on this. mainly all openapi spec structs are done. the problem now is that we are using sumtypes in the structs, and currently it is not supported to decode json into sumtypes (https://github.com/vlang/v/issues/15081).
still need to figure a workaround, maybe somehow drop the sumtypes, or use the x.json2 module.

**Comment by despiegk** [comment]
"we are using sumtypes in the structs" or they are using it?

**Comment by despiegk** [comment]
if too hard we can skip the task for now but we need communication
