### ISSUE TITLE
Extend osal/done to save key/values to disk

### ISSUE THREAD

**Issue by keraf** [crystaluniverse/crystallib#313]
Currently `osal/done` is a key/value store that keeps data in memory. We want it to persist data on disk and load it when the retrieve functions are called.

https://github.com/freeflowuniverse/crystallib/blob/development_db/crystallib/osal/done.v

**Comment by ashraffouda** [comment]
i checked it, and this is already implemented https://github.com/freeflowuniverse/crystallib/blob/development_db/crystallib/osal/done.v#L156
