### ISSUE TITLE
finish doctree module

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#323]
https://github.com/freeflowuniverse/crystallib/blob/development_integration/crystallib/data/doctree/readme.md

please complete this module

**Comment by mariobassem** [comment]
progress update:

- link fixing is now working, still need to add some testing for it
- added tests for error reports in a collection

**Comment by despiegk** [comment]
test by parsing a full mdbook wiki, then generate the mdbook wiki, then parse again, and compare should be the same

**Comment by despiegk** [comment]
done
