### ISSUE TITLE
build system using podman +++ 

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#354]
> branch: development_podman

## deliverable 1: v builder

* pacstrap arch in directory
* use buildah to install V (use our installers: the bash scripts downloaded see readme in home crystal)
* package as std container image
* use podman to start the image and give it a .v file to make binary, this binary is available on host
* exampke how to compile hero, have available in host ~/hero/bin/...

## deliverable 2: installers s3 server & yggdrasil in V

* make command in hero for installing s3 server & yggdrasil (2 installers)
* s3 server already exists (was from lee, see if it all works)
* make sure can be called using heroscript

```js
!!hero_s3.install start:1 secret:'aaa' ... 
!!hero_yggdrasil.install start:1 secret:'aaa' ... 
```

## deliverable 3: s3server image

* pacstrap arch in directory
* use buildah to copy hero cmdline into build env (as was built before)
* call hero with heroscript to install s3 server (now we can use hero in the container env to do stuff for us)
* make image with buildah
* use podman to start image and see s3 server is working

## deliverable 4: yggdrasil image

* pacstrap arch in directory
* use buildah to copy hero into build env
* call hero with heroscript to install yggdrasil
* make image
* use podman to start image and see yggdrasil is working
* see how to link route from local host os into this image (basically use yggdrasil container as router for yggdrasil)

## deliverable 5: example of basic build cycle for flist

* make sure s3server & yggdrasil is working
* pacstrap arch in directory
* use buildah to install some software & set entry point
* use zinit as initial process
* use flistv2 to create flist and put date in the local s3 server
* remove build env
* start a container with podman using the flist, see it works (so container booting from flist)
* use tfrobot (through v-wrapper) to deploy the created flist on grid, connect to it over yggdrasil using our router

question: can zos use S3 server over yggdrasil?

## deliverable 6: example with 2 stage build

* use arch to build
* create new layer where only the resulting binary e.g. a golang binary or so is
* create smallest possible flist for a specific binary

## deliverable 7: build mdbook/zola image

* use arch to build
* use 2 layer approach
* there are hero installers, need to be used
* make smallest possible flist

## technical remarks

* use arch
* use pacstrap to get started
* see how to remove data we don't need after building (cleanup container to only have relevant parts)

**Comment by ashraffouda** [comment]
paused waiting for this https://github.com/freeflowuniverse/crystallib/issues/384 and this https://github.com/freeflowuniverse/crystallib/issues/385

**Comment by ashraffouda** [comment]
deliverable6 https://github.com/freeflowuniverse/crystallib/pull/387
