### ISSUE TITLE
rfs installer

### ISSUE THREAD

**Issue by mariobassem** [crystaluniverse/crystallib#384]
create an installer for rfs

**Comment by mariobassem** [comment]
progress update:
- rfs mount is a blocking process, should run in the background. for some reason this is not working with the `-d` flag, and also something goes wrong when using screen. needs to be further investigated. 
- it's worth mentioning that running the process manually works fine.

**Comment by ashraffouda** [comment]
fixed by this https://github.com/freeflowuniverse/crystallib/pull/383
