### ISSUE TITLE
hero mdbook: SUMMARY.md issue in formatting

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#394]
# Situation

* currently mdbook SUMMARY.md and hero mdbook SUMMARY.md aren't treated the same way, for at least one point:
  * parenthesis in a heading gets triggered as a URL as the SUMMARY.md tempalte is [...](...), looks like [...(...)](...) separates the final version (see screenshot)
* With mdbook alone, this works:

```
    - [What is the difference between Internet capacity and connectivity? Does ThreeFold replace my Internet service provider (ISP)?](#what-is-the-difference-between-internet-capacity-and-connectivity-does-threefold-replace-my-internet-service-provider-isp)
```

* with hero mdbook, it generates this:
  ![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/c8227741-bf3f-447b-b25f-bef2b10cb40b)

# Proposition

* Maybe we can set that the code first try to build with mdbook alone, then process with the other method? Or we need to make sure that no "feature" by mdbook are broken when passed to hero mdbook

**Comment by mik-tf** [comment]
# Another Example

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/85f2df33-c0a9-4f7f-816d-198a1c514a46)

**Comment by mik-tf** [comment]
Also: if there is a \# Summary Title on the SUMMARY.md file, the book won't build

**Comment by despiegk** [comment]
we need to have it all working in hero, because its a pre-processor

**Comment by despiegk** [comment]
maybe for now just remove incompatible items like the ( ) ...

**Comment by despiegk** [comment]
please let us know if there are real showstoppers, then we will fix asap
