### ISSUE TITLE
feature request: allow to keep markdown/mdbook directory tree structure for URLs in summary.md

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#395]
# Situation

- currently, when using hero mdbook to build an mdbook, the URL in summary.md are modified:

- in books/SUMMARY.md
![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/4cbb8b71-ad88-4f08-94a9-fd8f8f63bf22)
- in hero/var/mdbuild/info_grid/src/SUMMARY.md
![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/62296d36-bea7-43c2-a54c-84b9700a7e55)

# Request

- can we add a parameter that allows the user to keep the same directory tree as with mdbook? 
  - this would make all the hero mdbook books compatible with markdown files, mdbooks and github, to name a few. 
- otherwise links from actual mdbooks won't be compatible when built with hero mdbook (e.g. documentation/dashboard/deploy.md becomes documentation/deploy.md)

**Comment by mik-tf** [comment]
Another example of what this means:

- Before hero mdbook processing, the file has the following URLs (folder/subfolder/subolder/file.md):
![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/64b5f35d-0d7b-46e7-96f4-67e50d0b1a45)

- After hero mdbook, the file has those URLs (collection_name:file.md):

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/763e1fc0-f732-4f40-ad1a-dd044e8a9872)

- We can see that the process has the result of losing the URLs.
- Not only this but files from collection documentation are all changed to the collection intro.
- Markdown files in general use this kind of directory organization, so for example on github, info_grid can be browsed and all links work as with the pre-hero mdbook processed files: see here https://github.com/threefoldtech/info_grid/blob/development/src/SUMMARY.md

- The link intro:dashboard has this output:
![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/aff62606-c540-4071-8eac-f0002646477d)

**Comment by despiegk** [comment]
its the full point of the tool, the exported structure is compatible because it all puts it in 1 dir without subdirs,
the links are reformatted by the tool, no need for you to do it

its always collection/.../name.md ... can be anything

its true that browsing on github is something we might loose, but we win a lot too

- link fixing
- reuse between collections
- macro support
- includes between collections
- links with nothing more than mentioning the collection name
- independent git management for collections

....

we need to enable automatic building thats for sure

the exported format is compatible with any further tool

**Comment by mik-tf** [comment]
I understand the motive. But what about having the option to keep the URL path?

Since, as it is now, I do think this limits the versatility of hero by "losing" this faculty of mdbook. Ideally, IMO, hero would add features to mdbook while being able to support existing mdbook features.

I would think it would be possible for hero to support those 2 modes. In short, practically this could amount to adding a parameter (say boolean true/false named set_collection_path = true) that would set the URL with collection/file_name (when false) and collection/path/to/file_name (when true).

In this case when the parameter would be set to true, hero could be able to differentiate files with their file path, e.g.:

- collection1/folder1/file_name.md
- collection1/folder2/file_name.md

And not only this, but then this means that the URLs/hyperlinks of any conventional mdbook would fit with hero mdbook. That might help the adoption of hero mdbook by people using standard mdbook!

In brief, one big advantage of having this possibility (parameter set_collection_path) is that any mdbook would then be able to be converted into a hero mdbook without any change in the whole SUMMARY.md as well as URLs, without any worries if different files have the same name.

Just some suggestions. I understand if we don't want to go this route with hero. I simply wanted to provide some ideas to improve the versatility of hero from my perspective.

**Comment by mik-tf** [comment]
@despiegk 

Also, I can create another issue but there is also this issue:

- files from collection **documentation** are all changed to the collection **intro**
- e.g. documentation/.../dashboard.md becomes intro/dashboard.md

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/ea2f408f-8dc2-4413-9ee7-24f2c53da4fa)

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/237a53d7-201a-416c-9915-bef63930d408)

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/730236bf-28ec-4e33-9c47-58e8a40cffda)

EDIT: Made a separate issue #401
