### ISSUE TITLE
hero mdbook, some markdown is not parsed

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#403]
# Situation

Some markdown is not parsed:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/b80034ae-5b69-46a8-8d4c-0e66b947947a)

```
- `charts`: helm chart
- `cmds`: includes the project Golang entrypoints
- `docs`: project documentation
- `internal`: contains the explorer API logic and the cert manager implementation, this where most of the feature work will be done
- `pkg`: contains client implementation and shared libs
- `tests`: integration tests
- `tools`: DB tools to prepare the Postgres DB for testing and development
- `rootfs`: ZOS root endpoint that will be mounted in the docker image
```

It should be like this:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/05e7ffe1-05c4-439a-af2d-a051f5499b4c)

**Comment by mik-tf** [comment]
Another example:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/020ad3c4-4625-4d64-b624-8c0729966642)

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/1c54ac21-128f-4b5f-9d81-2ac593020fbc)

It should be this:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/f5f0303a-acb2-4ade-8d40-7ea5c0dac54a)

**Comment by despiegk** [comment]
can you check this and let me know please @MarioBassem
