### ISSUE TITLE
hero features request

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#405]
# hero mdbook features requests

Working on transferring an existing mdbook to hero mdbook (with over 2000 pages and complex features of mdbook), there are some features that could be added to hero mdbook (or simply not removed from the basic mdbook functionality) to improve its use case and enable higher compatibility with markdown files.

- [x] allow to set a book.toml file to set things such as the print button, to set fold layers, etc. (see [info_grid book.toml](https://github.com/threefoldtech/info_grid/blob/development/book.toml))
    - will be for future
    - fix here: https://github.com/freeflowuniverse/crystallib/pull/423
- [x] allow hero mdbook to use specific preprocessors (e.g. [last-changed](https://github.com/badboy/mdbook-last-changed))
    - just tell us which preprocessors we need to include
    - fix here https://github.com/freeflowuniverse/crystallib/pull/415
- allow to set a theme directory (e.g. [see here in info_grid](https://github.com/threefoldtech/info_grid/tree/development/theme), we added a dashboard button to the manual)
![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/b5af5317-f323-4b95-94a4-4d38bed58683)
   - future
   - can work later
- allow hero to not put all titles of markdown files in lower cases
   - the titles shouldn't be the files are, do you mean files or titles in the documents
   - not important for now
- [x] allow parentheses in Table of contents (e.g. in SUMMARY.md)
    - future, please work around it
    - fix here: https://github.com/freeflowuniverse/crystallib/pull/425
- [x] just like we have hero converting URLs to (collection_name:file_name.md), we could have that hero converts the mdbook include into the hero mdbook include:
    - dont understand , include does support other collections
    - fix here: https://github.com/freeflowuniverse/crystallib/pull/426
  ```
  # hero include
  !!wiki.include page:'collection_name:file_name.md'
  # mdbook include
  {{#include /path/to/file/file_name.md}}
  ```

Note that those are standard mdbook features that are not available on hero mdbook. The idea is to know the current state of hero to create proper docs. Priorities would be using the book.toml file, specifying preprocessors and setting changes in the theme (.hbs file).

> it should not be needed for people to specify book.toml

E.g. if we don't change/until we change the parentheses option in TOC, we can at least document the situation in the manual so users know how to use hero efficiently, in this case not using parentheses in TOC.

# Notes on Resources

These features don't have the same priority. We can see which features can be put for a later phase.

# Hero Docs (WIP)

Hero basics: https://git.ourworld.tf/tfgrid/info_tfgrid/src/branch/main/docs/hero_mdbook_fullvm.md
Create new hero mdbook: https://git.ourworld.tf/tfgrid/info_tfgrid/src/branch/main/docs/hero_create_mdbook.md

**Comment by despiegk** [comment]
@Mik-TF see my addons in text above, should prob have done here

**Comment by mik-tf** [comment]
Here is the issue for the preprocessor to add: https://github.com/freeflowuniverse/crystallib/issues/413

**Comment by mik-tf** [comment]
" allow hero to not put all titles of markdown files in lower cases
the titles shouldn't be the files are, do you mean files or titles in the documents"

If you have a file with uppercase in the title e.g. FILENAME.md, after hero mdbook converts the file, the file is named "filename.md". So it loses the uppercase.

**Comment by mik-tf** [comment]
"dont understand , include does support other collections"

I am saying hero mdbook could convert the standard mdbook include to the hero mdbook include, e.g.

this

`{{#include /path/to/file/file_name.md}}`

would be converted to

`!!wiki.include page:'collection_name:file_name.md'`

Just a proposition.

**Comment by mik-tf** [comment]
" allow parentheses in Table of contents (e.g. in SUMMARY.md)
future, please work around it"

Yes I did find a work around. It's indeed for the future. I wrote it as a reference so we document the differences between mdbook and hero mdbook.

**Comment by mik-tf** [comment]
Closing as the most important issues are taken care of in current PRs.
