### ISSUE TITLE
mdbook has issues with unlisted pages

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#410]
see https://friends.threefold.info/habaricloud/legal/terms_conditions_all3.html
(planet/first)

the terms and conditions are not used in any page, yet still if produces this problem,

**Comment by mariobassem** [comment]
i don't understand where the issue is, can you be more specific? what do you mean by "this problem" ??

**Comment by mik-tf** [comment]
@MarioBassem 

hero mdbook adds pages in the additional pages section. Those added pages are supposed to be in SUMMARY.md or called directly in a page (e.g. intro.md is not in summary but you call it in page.md, then it will be added in the additional page). But Kristof says some pages are not in SUMMARY.md or anywhere else, but they still appear in the additional page.

My bet is that we can fix this issue around here: https://github.com/freeflowuniverse/crystallib/blob/323262e236927c370af24e23d71451ae2097bf16/crystallib/webtools/mdbook/mdbook.v#L124

I hope it's clear!

**Comment by mariobassem** [comment]
@Mik-TF if you have an example book with the issue that would be great too :D

**Comment by mik-tf** [comment]
I think a good example is provided by Kristof at the link above:

see https://friends.threefold.info/habaricloud/legal/terms_conditions_all3.html
username: planet, password: first

Let me know if this is sufficient.

**Comment by mariobassem** [comment]
i believe this is a non-issue. if page A is in summary, and mentions page B, page B is added to unlisted pages, page B is then explored, and all pages mentioned in it will also be added to unlisted pages, and so on...
