### ISSUE TITLE
Hero Mdbook collection:filename.md not working

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#428]
# Situation

When we set the following.

```

[Link Example](developers/grid3_supported_flists.md)

[Link Example](developers/grid3_supported_flists#introduction.md)

[Link Example](../developers/grid3_supported_flists.md)

[Link Example](../developers/grid3_supported_flists#introduction.md)

[Link Example](developers:grid3_supported_flists)

[Link Example](developers:grid3_supported_flists#introduction.md)
```

This is the output:

```
[Link Example](dashboard:grid3_supported_flists.md)

[Link Example](dashboard:grid3_supported_flists#introduction.md)

[Link Example](dashboard:grid3_supported_flists.md)

[Link Example](dashboard:grid3_supported_flists#introduction.md)

[Link Example](grid3_supported_flists.md)

[Link Example](grid3_supported_flists#introduction.md#introduction.md)
```

# Conclusion

None of those links work. We can see that in all cases the collection should be developers but it gets changed to dashboard.

On the two last, we can see that using collection:filename.md, we lose the collection name.

I think collection:filename is not working correctly.

**Comment by mik-tf** [comment]
@despiegk this should be the priority, along with #417 

Once those 2 issues are set, hero mdbook can be used to production and we'll have functioning mdbooks!

**Comment by MarioBassem** [comment]
can you provide steps to reproduce? (i.e. commands to run on which input)

**Comment by mik-tf** [comment]
@MarioBassem I'll show some steps to reproduce two things to fix:

- clone repo: https://git.ourworld.tf/tfgrid/info_tfgrid in ~/code/git.ourworld.tf/tfgrid (should be root, sudo su)
- cd into info_tfgrid
- checkout the branch development_test_toc
- build the book with mdbook: hero mdbook -p $(pwd)/heroscript/test
- Go to the hero mdbook directory built: cd ~/hero/var/mdbuild/test
- Serve the book: mdbook serve --port 3003
- you can see that the file Cloud TOC has the url cloud/cloud_toc

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/90107b11-5838-40ca-8876-bc38025ef487)

- but if you go on the first page (test page) and click on either of those links:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/a945aeae-d7c0-436b-9600-cd732a88959b)

- it leads to test/cloud_toc and not cloud/cloud_toc. And for this reason, the file is situated into Additional Pages:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/3878fb1d-b169-4fb3-9bc6-b2c8fbdd2a07)

- expected behaviour: it should go to cloud/cloud_toc

---

- the other problem is the following: we can't go to a different collection with subsection (\#)
- if you click on this link: it should go to cloud/cloudunits.html#compute-capacity
![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/d44e199d-0123-4135-b181-1cef2e4a478a)
- but instead it goes to this:
![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/f2d47224-2de8-469f-a11d-8fdb22361c7d)

---

# Codes

The codes are the following:

```

# Test

Go to the [cloud section](cloud:cloud_toc)

Go to the [cloud section](cloud:cloud_toc.md)

# Test 2

Go to the [cloud units](cloud:cloudunits.md#compute-capacity)

```



---
Let me know if you need more info! Thanks!

**Comment by despiegk** [comment]
will be resolved when we add unlisted pages
