### ISSUE TITLE
hero mdbook parsing error codes with tabs

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#432]
# Situation

For now, hero mdbook can't parse codes with tabs:

```
- Clone the repository
  - ```bash
    git clone https://github.com/threefoldtech/tfgrid-sdk-ts
    ```
- Install the Grid Client
  - With yarn
      -   ```bash
          yarn install
          ```
  - With npm
      -   ```bash
          npm install
          ```
```

Will be shown as:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/27f37a06-2da2-4e73-83f1-975a84c3cbf6)

# Todo

- Make sure we follow markdown output to html as much as possible

# Meantime

In the meantime, we can make sure the info_tfgrid mdbooks don't use this syntax

**Comment by mariobassem** [comment]
needs refactoring as list contents are parsed as paragraphs (e.g. defs, comments, text, links), they can't contain code blocks for now. 
technically same as https://github.com/freeflowuniverse/crystallib/issues/409

**Comment by despiegk** [comment]
this is not supported, 
please add to manual

**Comment by mik-tf** [comment]
Added info on the manual: Done on both info_tfgrid and info_tfgrid_private. 

Just a note: this really reduces the aesthetics of guides on the manual. It's easier to follow for the eyes when you have tabs with codes. But I understand the situation.

Closing the issue thanks @despiegk and @MarioBassem
