### ISSUE TITLE
hero mdbook bug: table of contents can't go to H3

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#434]
# Situation

- hero mdbook bug: table of contents can't go to H3

# How to reproduce

- write a file with a table of contents, which goes to H3. The mdbook file rendered by hero contains the H3 level but not the table of contents.

- the original markdown file toc is the following

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/c584621b-b155-4080-a3fb-d9564a74623d)

- the original markdown file in preview mode is the following

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/c2e80eab-c515-4cef-a622-889cd4dfea8f)

- the hero markdown file rendering is the following

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/5c460446-70a8-4100-b5d3-44f8c2aeb0ed)

- the code of this rendered file is the following

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/c62b7ec4-7036-48e4-b95b-208fe619b193)

- the headings are OK in the text (see H3, H4, ...)

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/13f459bc-ffbf-4e31-a1fe-dbd7fdf8e3b5)

# Conclusion

The issue is how the table of contents is parsed. There are tabs missing to get a different heading level.

**Comment by mariobassem** [comment]
I'm a bit confused. i tried to check the indentation level of list items and it works fine. what is the issue with headers?
I know screenshots are useful, but can you provide the actual steps to reproduce so that i can redo them on my machine? (like the command you ran and on which input)

**Comment by mik-tf** [comment]
@MarioBassem Gotcha.

So steps:

- clone repo: https://git.ourworld.tf/tfgrid/info_tfgrid in ~/code/git.ourworld.tf/tfgrid (should be root, sudo su)
- cd into info_tfgrid
- checkout the branch development_test_toc
- build the book with mdbook: hero mdbook -p $(pwd)/heroscript/test
- Go to the hero mdbook directory built: cd ~/hero/var/mdbuild/test
- Serve the book: mdbook serve --port 3003
- You can see that the table of contents doesn't allow for a "3rd" level

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/86bc8bbb-33a1-4276-af39-1532ed3000fa)


The code is the following:

```
<h2>Table of Contents</h2>

- [Introduction](#introduction)
- [Prerequisites](#prerequisites)
- [Creating a New mdbook](#creating-a-new-mdbook)
  - [Cloning the mdbook Repository](#cloning-the-mdbook-repository)
  - [Directory Tree Example](#directory-tree-example)
  - [Files and Directories Example](#files-and-directories-example)
    - [books](#books)
    - [collections](#collections)
    - [heroscript](#heroscript)
    - [LICENSE](#license)
    - [README](#readme)
- [Generating the Mdbook Locally](#generating-the-mdbook-locally)
- [Pushing the Changes](#pushing-the-changes)
- [Generating the Mdbook from a Remote Repository](#generating-the-mdbook-from-a-remote-repository)
```

and the output should be:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/ff550a5c-bf72-438a-a4ce-4872e467d689)

---

Let me know if you need more info! Thanks!

**Comment by mariobassem** [comment]
@Mik-TF thanks.
i traced this, and the problem here is in the number of whitespace characters used. if you stick with tabs instead of whitespaces your problems will go away. 
but in general we calculate the indentation level by taking the ceil of the number of whitespaces divided by 4. this means that 0 whitespaces is at level 1, [1,2,3,4] at level 2, [5,6,7,8] at level 3, and so on.

**Comment by mik-tf** [comment]
Yes I understand but mdbook's TOC create this TOC automatically so I can't change it.

I understand that hero mdbook parses differently than mdbook/markdown then. Anything we can do?

**Comment by mariobassem** [comment]
refactored list parsing to handle this case correctly
