### ISSUE TITLE
allow the Redis client to detect properly a closed socket and attempt to reconnect

### ISSUE THREAD

**Issue by sameh-farouk** [crystaluniverse/crystallib#64]
currently, if the server process is terminated (Redis), the connection won't be re-established if the server comes up again.
the suggestion is to pass a flag to the Redis client instance configuration to specify if we want the client to wait for the server and try to re-establish the connection if dropped.
also, we need a proper way to handle both sockets' read/write errors as well as the zero length string that could be received from the socket after being terminated from the server-side.

**Comment by despiegk** [comment]
should be working now but I am sure we need to test better, there will still be issues I think
also need to check if bug with vlang is still there in examples of the redisclientcore

**Comment by despiegk** [comment]
is there a defer statement?

**Comment by sameh-farouk** [comment]
> is there a defer statement?

@despiegk yes
```
defer { }
```
https://github.com/vlang/v/blob/master/doc/docs.md#defer
