### ISSUE TITLE
pdf macro support

### ISSUE THREAD

**Issue by xmonader** [crystaluniverse/crystallib#65]
add support for pdf macro, it should accept the PDF's url as a param, and it should render the pdf viewer 

pdf viewer:
- has tracking capabilities for the session
- works on full screen

**Comment by MohamedEssamAdawy** [comment]
**Updates**
- Depends on tf-pdf: https://github.com/threefoldtech/tf-pdf, (previous, next working now)
- Tracking already done using tf-tracker, will track the whole page, right ?
- fullscreen still in-progress

**Comment by MohamedEssamAdawy** [comment]
**Updates**
- Fullscreen done
- Enhancement in the control toolbar

**Comment by MohamedEssamAdawy** [comment]
Merged
