### ISSUE TITLE
publishtools fail developing the wiki

### ISSUE THREAD

**Issue by Omarabdul3ziz** [crystaluniverse/crystallib#71]
got this when running `publishtools develop` in the `wiki_config/` 
![Screenshot from 2022-05-18 17-21-53](https://user-images.githubusercontent.com/32527347/169079671-337b68b7-21de-4dec-a086-c1a270f008e1.png)

**Comment by sameh-farouk** [comment]
there was invalid content on the wikis content
https://github.com/threefoldfoundation/info_manual3/blob/development/wiki/tfchain_portal/tfchain_portal_home.md?plain=1

I pushed a fix here
https://github.com/threefoldfoundation/info_manual3/commit/ae2fcb1e100c0155f0bc449282c55177f90c0020

links to files in the wiki expected to be MD files and shouldn't have `.md` extension in the end.

the issue should be solved now.

**Comment by Omarabdul3ziz** [comment]
it works now
