### ISSUE TITLE
a lot of previously written code has `import` with outdated module name

### ISSUE THREAD

**Issue by sameh-farouk** [crystaluniverse/crystallib#75]
the module name has been changed as below
`despiegk.crystallib` -> `freeflowuniverse.crystallib`

These changes are due to a change previously made to the module author name.
now, when you install the v module, it goes to `~/.vmodules/freeflowuniverse/crystallib`, not to the old path.

now, I have seen some code and scripts have a workaround by copying the content of the module to `despiegk` directory where the code with the outdated import is expected to find the module. but this seems very wrong and looks ugly.

should we do a clean to the old code base to change `import` to point to the correct module name? instead of having duplicated files in two different directories, and a non-standard way to install our crystallib v module and other the modules that depends on it.

**Comment by despiegk** [comment]
please make the change on development_refactor...
