### ISSUE TITLE
support threefold connect login flow

### ISSUE THREAD

**Issue by xmonader** [crystaluniverse/crystallib#78]
see if can be done as middleware in vweb

**Comment by Mahmoud-Emad** [comment]
Still working on it.

login and callback endpoint were implemented, but there are some issues I work on.
I need to generate an SSL certificate to receive requests over HTTPS after Threefold redirects me to the callback endpoint.

**Comment by Mahmoud-Emad** [comment]
Right now still working on it, working on signing the key part, and decrypting it.

**Comment by Mahmoud-Emad** [comment]
Still working on the decrypt method issue.

**Comment by Mahmoud-Emad** [comment]
Added some refactor to the code and make sure that everything is working well except the `genrate_keys` function.
* TODO: 
    - will generate a secret key and save it into a file, just want the V team to update some code in the `Libsodium` package

**Comment by Mahmoud-Emad** [comment]
#### Done:
 * generate new keys and save them into `keys.toml` file
  
#### NOTE: 
* If this is the first time running the application you must run the `create_keys` file to generate the keys, other ways it will be taken from the file directly

**Comment by despiegk** [comment]
needs to be merged in development38 ... 
make sure docs are available
and timur understands how to do it

**Comment by xmonader** [comment]
there's a README in the PR, if anything not clear please open issues
