### ISSUE TITLE
expand the twinclient2 to match the modules on the ts client (tfchain, stellar, algorand)

### ISSUE THREAD

**Issue by xmonader** [crystaluniverse/crystallib#85]
- [x] tfchain
- [x] stellar
- [x] algorand

**Comment by abom** [comment]
Twin client: https://github.com/freeflowuniverse/crystallib/tree/development_refactor3-gridclient_over_ws/twinclient2
TS client modules: https://github.com/threefoldtech/grid3_client_ts/tree/864b3b031686d8712149c219a30ccce26de96724/src/modules

For testing, you can use https://github.com/freeflowuniverse/twinactions/tree/development_tfgrid_websocket_server_proper/pocTS

**Comment by Mahmoud-Emad** [comment]
TFChain methods were Implemented inside `tfchain.v` file to communicate with TSGridClient over WS
