### ISSUE TITLE
webserver for V with authentication, tfconnect, ... 

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#92]
https://docs.google.com/document/d/18doP7aNhGEu0RxR9AXlOHk3Me7UqrH5UeUkMuWTRiGo/edit

**Comment by despiegk** [comment]
timur already created some things here, need to make sure documentation is on right spot,
kristof needs to sign off
and make sure tfconnect login also supported (as add on)

**Comment by despiegk** [comment]
should probably move to spiderlib

**Comment by despiegk** [comment]
lets update docs so at least we know what we have and what we can start with

**Comment by timurgordon** [comment]
done, authentication modules can be found at spiderlib/auth.
